# Generated by Django 5.2.7 on 2026-02-09 07:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(choices=[('clinical_psychologist', 'Clinical Psychologist'), ('counselor', 'Counselor'), ('psychiatrist', 'Psychiatrist'), ('therapist', 'Therapist'), ('social_worker', 'Social Worker')], max_length=30)),
                ('contact_info', models.TextField(help_text='Phone, email, or website')),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
            },
        ),
        migrations.CreateModel(
            name='HeritageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('historical_context', models.TextField(help_text='Historical background')),
                ('practice', models.TextField(help_text='Traditional practice or wisdom')),
                ('relevance_today', models.TextField(help_text='How it applies to modern life')),
                ('source', models.CharField(blank=True, help_text='Source reference', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Heritage Content',
                'verbose_name_plural': 'Heritage Content',
            },
        ),
        migrations.CreateModel(
            name='RecoveryProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_days', models.IntegerField(default=30)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recovery Program',
                'verbose_name_plural': 'Recovery Programs',
            },
        ),
        migrations.CreateModel(
            name='TraumaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Family', 'Family Trauma'), ('Financial', 'Financial Stress'), ('Career', 'Career Anxiety'), ('Love', 'Relationship Trauma')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='❤️', max_length=50)),
                ('color_code', models.CharField(default='#FF9933', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trauma Type',
                'verbose_name_plural': 'Trauma Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_mood', 'Persistent Low Mood'), ('crisis', 'Crisis Detected'), ('milestone', 'Milestone Achieved'), ('reminder', 'Activity Reminder')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood_score', models.IntegerField(help_text='1=Very Bad, 5=Very Good', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mood Log',
                'verbose_name_plural': 'Mood Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('activity_type', models.CharField(choices=[('meditation', 'Meditation'), ('exercise', 'Physical Exercise'), ('journaling', 'Journaling'), ('breathing', 'Breathing Exercise'), ('therapy', 'Therapy Session'), ('reading', 'Educational Reading'), ('practice', 'Practical Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('resources', models.TextField(blank=True, help_text='Links, videos, or additional resources')),
                ('estimated_duration_minutes', models.IntegerField(default=15)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.recoveryprogram')),
            ],
            options={
                'verbose_name': 'Recovery Step',
                'verbose_name_plural': 'Recovery Steps',
                'ordering': ['program', 'day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
        migrations.AddField(
            model_name='recoveryprogram',
            name='trauma_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_programs', to='core.traumatype'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight for this question (0.1 to 3.0)', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)])),
                ('is_critical', models.BooleanField(default=False, help_text='Mark if this question is critical for assessment')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trauma_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.traumatype')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['trauma_type', 'order'],
                'unique_together': {('trauma_type', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ModernProgressContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('modern_solution', models.TextField()),
                ('therapy_type', models.CharField(blank=True, choices=[('cbt', 'Cognitive Behavioral Therapy'), ('mindfulness', 'Mindfulness-Based Therapy'), ('emdr', 'EMDR'), ('dbt', 'Dialectical Behavior Therapy'), ('psychotherapy', 'Psychotherapy'), ('group_therapy', 'Group Therapy')], max_length=20)),
                ('scientific_basis', models.TextField(help_text='Research or evidence supporting this')),
                ('resources', models.TextField(blank=True, help_text='Books, apps, websites')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('heritage_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modern_solutions', to='core.heritagecontent')),
                ('trauma_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_content', to='core.traumatype')),
            ],
            options={
                'verbose_name': 'Modern Progress Content',
                'verbose_name_plural': 'Modern Progress Content',
            },
        ),
        migrations.AddField(
            model_name='heritagecontent',
            name='trauma_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heritage_content', to='core.traumatype'),
        ),
        migrations.CreateModel(
            name='GovtScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('link', models.URLField(max_length=500)),
                ('state', models.CharField(blank=True, help_text="Specific to state, or 'National'", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trauma_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='govt_schemes', to='core.traumatype')),
            ],
            options={
                'verbose_name': 'Government Scheme',
                'verbose_name_plural': 'Government Schemes',
            },
        ),
        migrations.CreateModel(
            name='DominantTrauma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(help_text='ML confidence (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dominant_trauma', to=settings.AUTH_USER_MODEL)),
                ('primary_trauma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_for_users', to='core.traumatype')),
                ('secondary_trauma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_for_users', to='core.traumatype')),
            ],
            options={
                'verbose_name': 'Dominant Trauma',
                'verbose_name_plural': 'Dominant Traumas',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, choices=[('18-25', '18-25 years'), ('26-35', '26-35 years'), ('36-45', '36-45 years'), ('46-60', '46-60 years'), ('60+', '60+ years')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('te', 'Telugu')], default='en', max_length=5)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='TraumaScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], max_length=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trauma_scores', to=settings.AUTH_USER_MODEL)),
                ('trauma_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.traumatype')),
            ],
            options={
                'verbose_name': 'Trauma Score',
                'verbose_name_plural': 'Trauma Scores',
                'ordering': ['-calculated_at'],
                'unique_together': {('user', 'trauma_type', 'calculated_at')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': 'User Answers',
                'ordering': ['-answered_at'],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserRecoveryProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=15)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="User's personal notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.recoverystep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recovery Progress',
                'verbose_name_plural': 'User Recovery Progress',
                'unique_together': {('user', 'step')},
            },
        ),
    ]
